### ISSUE TITLE
TS Fission Auth Lib

### ISSUE THREAD

**Issue by expede** [fission-suite/ts-sdk#2]
Probably will live in its own library, but tracking for now:

Needs to be able to:

* [ ] Create EdDSA key
* [ ] Store via WebAuthn
* [x] Retrieve key from `_did.someusername.fission.name` TXT record
* [x] Validate self-signed tokens via PK

**Comment by icidasset** [comment]
I think we can close this one?

**Comment by expede** [comment]
Good call
