### ISSUE TITLE
Link on npmjs.com points to keystore-idb

### ISSUE THREAD

**Issue by fubuloubu** [fission-suite/ts-sdk#62]
![Screenshot from 2020-07-16 15-02-04](https://user-images.githubusercontent.com/3859395/87711699-a44f8f80-c775-11ea-93dc-6da06cc9af00.png)

Not sure if this is intentional or not

**Comment by bmann** [comment]
It is not! Assigning to @dholms to fix. Thanks!

**Comment by icidasset** [comment]
@dholms I'll do this one, I'm doing the next release anyways.
